# simple Linear Regression

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("F:/ml_assets/dhaka_house_price.csv")
df

area   price
0    2600   55000
1    3000   62000
2    3200   66000
3    3600   68000
4    4000   72500
5    2500   50000
6    2700   59000
7    1200   26000
8    5000   99000
9    2500   50000
10   2100   48000
11   1800   35000
12   3000   63000
13   3600   69000
14   4200   76000
15   5000   98000
16   1100   20000
17   1900   39000

In [3]:
print(df.shape)


(18, 2)


In [4]:
x = df.iloc[:,:-1].values
y = df.iloc[:,1].values
x,y

(array([[2600],
        [3000],
        [3200],
        [3600],
        [4000],
        [2500],
        [2700],
        [1200],
        [5000],
        [2500],
        [2100],
        [1800],
        [3000],
        [3600],
        [4200],
        [5000],
        [1100],
        [1900]], dtype=int64),
 array([55000, 62000, 66000, 68000, 72500, 50000, 59000, 26000, 99000,
        50000, 48000, 35000, 63000, 69000, 76000, 98000, 20000, 39000],
       dtype=int64))

In [5]:
#ML model trainig the dataset

from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=.30,random_state = 1)

In [6]:
xtrain

array([[5000],
       [4000],
       [3000],
       [2100],
       [2600],
       [1900],
       [1100],
       [2500],
       [5000],
       [3000],
       [1800],
       [2500]], dtype=int64)

ytrain

In [8]:
from sklearn.linear_model import LinearRegression
lg = LinearRegression()

lg.fit(xtrain,ytrain)



LinearRegression()

In [23]:
pre = int(lg.predict([[2500]]))
pre

50487

In [34]:
acc = int(lg.score(xtest,ytest)*100)
print("Score :",acc,"%")

Score : 94 %


# Saving ML Model

In [35]:
import pickle as pk

with open ("simpleLinearRegression","wb") as file:
    pk.dump(lg,file)